spring.application.name=Joonggonara

# Thymeleaf 캐시 끄기 (수정 즉시 HTML 반영)
spring.thymeleaf.cache=false

# devtools 자동 리스타트 활성화
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/jg?characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=qwer1234
